# Generated by Django 4.2.14 on 2024-08-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_profiles"),
    ]

    operations = [
        migrations.AddField(
            model_name="profiles",
            name="email",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
